os:
  - linux

sudo: required
dist: trusty
language: rust
rust:
  - stable
  - beta

env:
  global:
    - HOST=x86_64-unknown-linux-gnu
    - CARGO_INCREMENTAL=0

addons:
  apt:
    packages:
      - libopenblas-dev
      - libssl-dev
      - liblapack-dev
      - gfortran

cache: cargo

before_cache:
  - rm -rf "$TRAVIS_HOME/.cargo/registry/src"
  - if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then cargo install cargo-tarpaulin; fi

script:
  - if [ "$TRAVIS_OS_NAME" = 'osx' ]; then export CC=gcc-9 FC=gfortran-9 LIBRARY_PATH=/usr/local/opt/gcc/lib/gcc/9; fi
  - rm -r ~/travis/.cargo/registry/src/github*/openblas-src*/
  - rm -r ~/travis/.cargo/registry/cache/github*/openblas-src*/
  - cargo clean
  - cargo build
  - cargo test -vv

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    # Uncomment the following line for coveralls.io
    # cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID

   Uncomment the following two lines create and upload a report for codecov.io
   cargo tarpaulin --out Xml
   CODECOV_TOKEN="33fe3b09-bd4c-42e0-8c25-8f721bc37689"
   bash <(curl -s https://codecov.io/bash)
  fi