[package]
name = "nymph"
version = "0.1.0"
authors = ["Rhys Newell <rhys.newell@uqconnect.edu.au>"]
edition = "2020"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ordered-float = "1"
ndarray = { version = "0.13.0", features = ["rayon"] }
ndarray-npy = "0.5.*"
ndarray-linalg = { version = "0.12", features = ["static"] }
rayon = "1.2.*"

